window.WYR_QUESTIONS = [
  {id:"q001",category:"superpowers",red:"Be able to fly, but only as fast as you can run",blue:"Be invisible, but only while holding your breath"},
  {id:"q002",category:"time",red:"Pause time for 10 seconds once a day",blue:"Rewind time by 1 minute once a week"},
  {id:"q003",category:"life",red:"Know exactly how your life ends",blue:"Know exactly when your life changes forever"},
  {id:"q004",category:"money",red:"Get ₹1 crore today",blue:"Get ₹10 lakh every year for life"},
  {id:"q005",category:"tech",red:"Lose your phone for a month",blue:"Lose the internet for a month"},
  {id:"q006",category:"food",red:"Give up pizza forever",blue:"Give up biryani forever"},
  {id:"q007",category:"travel",red:"Travel anywhere for free but always alone",blue:"Travel only once a year but take anyone with you"},
  {id:"q008",category:"social",red:"Be famous everywhere you go",blue:"Be wealthy but completely anonymous"},
  {id:"q009",category:"future",red:"Live on Mars for 5 years",blue:"Live under the ocean for 5 years"},
  {id:"q010",category:"weird",red:"Have a personal theme song everyone can hear",blue:"Have subtitles appear whenever you speak"},
  {id:"q011",category:"skills",red:"Master every programming language",blue:"Speak every human language fluently"},
  {id:"q012",category:"sleep",red:"Never need sleep again",blue:"Sleep 10 hours every night and always wake up perfect"},
  {id:"q013",category:"career",red:"Have your dream job with average pay",blue:"Have a boring job with incredible pay"},
  {id:"q014",category:"memory",red:"Remember every single thing you experience",blue:"Forget any memory whenever you choose"},
  {id:"q015",category:"superpowers",red:"Read minds for 30 seconds a day",blue:"See 30 seconds into the future all day"},
  {id:"q016",category:"social",red:"Always know when someone is lying",blue:"Always know what someone really thinks of you"},
  {id:"q017",category:"money",red:"Own your dream house anywhere",blue:"Own your dream car collection forever"},
  {id:"q018",category:"funny",red:"Sneeze glitter",blue:"Hiccup tiny bubbles"},
  {id:"q019",category:"food",red:"Only eat sweet food for a year",blue:"Only eat spicy food for a year"},
  {id:"q020",category:"time",red:"Repeat your best day once",blue:"Erase your worst day completely"},
  {id:"q021",category:"games",red:"Be the best player in every video game",blue:"Be the best player in every sport"},
  {id:"q022",category:"future",red:"Own a robot that does every chore",blue:"Own a vehicle that can go anywhere"},
  {id:"q023",category:"weird",red:"Have a tiny dragon as a pet",blue:"Have a giant friendly wolf as a pet"},
  {id:"q024",category:"social",red:"Never feel embarrassed again",blue:"Never feel nervous again"},
  {id:"q025",category:"travel",red:"Live in a new country every year",blue:"Live in your favorite city forever"},
  {id:"q026",category:"career",red:"Start a risky company you believe in",blue:"Take a secure dream salary immediately"},
  {id:"q027",category:"tech",red:"Have unlimited battery on every device",blue:"Have perfect Wi-Fi everywhere on Earth"},
  {id:"q028",category:"money",red:"Get ₹10,000 every day",blue:"Get ₹5 crore once, right now"},
  {id:"q029",category:"life",red:"Be lucky in every small decision",blue:"Be extremely lucky once a year"},
  {id:"q030",category:"superpowers",red:"Teleport anywhere you have already been",blue:"Fly anywhere at 200 km/h"},
  {id:"q031",category:"music",red:"Hear your favorite song for the first time again",blue:"Meet your favorite artist for one hour"},
  {id:"q032",category:"movies",red:"Live inside your favorite movie universe",blue:"Live inside your favorite game universe"},
  {id:"q033",category:"food",red:"Get free restaurant food forever",blue:"Have a personal chef forever"},
  {id:"q034",category:"weird",red:"Have hair that changes color with your mood",blue:"Have eyes that glow whenever you are excited"},
  {id:"q035",category:"skills",red:"Learn any skill in one week",blue:"Never forget any skill once learned"},
  {id:"q036",category:"social",red:"Have 3 incredibly loyal friends",blue:"Have 100 casual friends everywhere"},
  {id:"q037",category:"future",red:"Visit Earth 1,000 years in the future",blue:"Visit Earth 1,000 years in the past"},
  {id:"q038",category:"money",red:"Never pay rent or EMI again",blue:"Never pay for food or travel again"},
  {id:"q039",category:"sleep",red:"Fall asleep instantly whenever you want",blue:"Wake up instantly without feeling tired"},
  {id:"q040",category:"funny",red:"Have a laugh that sounds like a car horn",blue:"Have a sneeze that sounds like a drum roll"},
  {id:"q041",category:"life",red:"Always arrive 20 minutes early",blue:"Always arrive exactly on time"},
  {id:"q042",category:"career",red:"Work 4 days a week forever",blue:"Work 6 months a year and take 6 months off"},
  {id:"q043",category:"travel",red:"Take a first-class flight anywhere once a month",blue:"Take unlimited economy flights forever"},
  {id:"q044",category:"tech",red:"Have the newest phone forever",blue:"Have the fastest laptop forever"},
  {id:"q045",category:"superpowers",red:"Control fire",blue:"Control water"},
  {id:"q046",category:"memory",red:"Replay any memory like a video",blue:"Share any memory with another person"},
  {id:"q047",category:"food",red:"Never drink coffee or tea again",blue:"Never eat dessert again"},
  {id:"q048",category:"social",red:"Get one brutally honest answer from anyone",blue:"Ask one question that everyone must answer"},
  {id:"q049",category:"money",red:"Have unlimited money but no fame",blue:"Be world-famous with a normal income"},
  {id:"q050",category:"weird",red:"Swap voices with anyone for a day",blue:"Swap heights with anyone for a day"},
  {id:"q051",category:"future",red:"Own an AI assistant that knows everything about you",blue:"Own a robot companion with a real personality"},
  {id:"q052",category:"games",red:"Never lose a board game again",blue:"Never lose an online multiplayer game again"},
  {id:"q053",category:"life",red:"Have perfect confidence",blue:"Have perfect discipline"},
  {id:"q054",category:"travel",red:"Spend a month in Antarctica",blue:"Spend a month in the Amazon rainforest"},
  {id:"q055",category:"skills",red:"Play every musical instrument",blue:"Draw and paint anything perfectly"},
  {id:"q056",category:"career",red:"Become a successful creator",blue:"Become a successful founder"},
  {id:"q057",category:"food",red:"Only eat breakfast foods",blue:"Only eat dinner foods"},
  {id:"q058",category:"superpowers",red:"Have super speed",blue:"Have super strength"},
  {id:"q059",category:"tech",red:"Delete social media forever",blue:"Delete streaming services forever"},
  {id:"q060",category:"funny",red:"Have a cat that can text you",blue:"Have a dog that can call you"},
  {id:"q061",category:"money",red:"Win ₹1 crore but everyone knows",blue:"Win ₹50 lakh and nobody ever knows"},
  {id:"q062",category:"time",red:"Get an extra hour every day",blue:"Get an extra day every month"},
  {id:"q063",category:"social",red:"Be able to make anyone laugh",blue:"Be able to calm anyone down"},
  {id:"q064",category:"future",red:"Know the next major invention",blue:"Know the next major global trend"},
  {id:"q065",category:"life",red:"Never get stuck in traffic",blue:"Never stand in a queue"},
  {id:"q066",category:"weird",red:"Have a room that changes to any scenery",blue:"Have a window that shows any place on Earth"},
  {id:"q067",category:"travel",red:"Explore space once",blue:"Explore every country on Earth"},
  {id:"q068",category:"career",red:"Be amazing at interviews",blue:"Be amazing at networking"},
  {id:"q069",category:"food",red:"Get unlimited street food",blue:"Get unlimited fine dining"},
  {id:"q070",category:"music",red:"Only listen to old songs forever",blue:"Only listen to new songs forever"},
  {id:"q071",category:"superpowers",red:"Freeze anything you touch",blue:"Heat anything you touch"},
  {id:"q072",category:"money",red:"Double your salary every 5 years",blue:"Get your dream salary immediately but never get a raise"},
  {id:"q073",category:"life",red:"Always make the right first impression",blue:"Always be remembered after one meeting"},
  {id:"q074",category:"tech",red:"Have unlimited cloud storage",blue:"Have unlimited mobile data everywhere"},
  {id:"q075",category:"funny",red:"Have background applause after every good idea",blue:"Have dramatic music before every important moment"},
  {id:"q076",category:"future",red:"Have a perfect digital clone of yourself",blue:"Have a perfect robot copy of yourself"},
  {id:"q077",category:"social",red:"Never be misunderstood",blue:"Always understand what others mean"},
  {id:"q078",category:"travel",red:"Live beside the ocean",blue:"Live beside the mountains"},
  {id:"q079",category:"skills",red:"Type at 300 words per minute",blue:"Read and remember a book in one hour"},
  {id:"q080",category:"weird",red:"Have gravity become half as strong for you",blue:"Be able to walk on any surface"},
  {id:"q081",category:"food",red:"Never need to cook again",blue:"Never need to clean dishes again"},
  {id:"q082",category:"career",red:"Work remotely from anywhere",blue:"Have a dream office five minutes from home"},
  {id:"q083",category:"money",red:"Get paid for every hour you sleep",blue:"Get paid for every kilometer you walk"},
  {id:"q084",category:"games",red:"Own every game ever released",blue:"Own the ultimate gaming setup forever"},
  {id:"q085",category:"superpowers",red:"Talk to animals",blue:"Talk to machines"},
  {id:"q086",category:"time",red:"Skip one awkward moment every day",blue:"Replay one funny moment every day"},
  {id:"q087",category:"social",red:"Have your crush text first",blue:"Always know exactly what to text back"},
  {id:"q088",category:"future",red:"Know what your life looks like in 10 years",blue:"Get one message from yourself 10 years in the future"},
  {id:"q089",category:"travel",red:"Always get a window seat",blue:"Never have a delayed flight"},
  {id:"q090",category:"funny",red:"Have every automatic door open dramatically for you",blue:"Have every elevator play your entrance music"},
  {id:"q091",category:"life",red:"Never lose your keys, wallet, or phone",blue:"Never forget a name or face"},
  {id:"q092",category:"tech",red:"Use a foldable laptop-sized phone",blue:"Use glasses that replace every screen"},
  {id:"q093",category:"skills",red:"Be incredible at public speaking",blue:"Be incredible at writing"},
  {id:"q094",category:"food",red:"Only drink water for a year",blue:"Only eat home-cooked food for a year"},
  {id:"q095",category:"money",red:"Have ₹5 crore at age 25",blue:"Have ₹50 crore at age 50"},
  {id:"q096",category:"weird",red:"Get one random useful superpower every Monday",blue:"Choose one small superpower and keep it forever"},
  {id:"q097",category:"career",red:"Build one legendary project",blue:"Build ten successful projects"},
  {id:"q098",category:"social",red:"Know everyone at a party",blue:"Know exactly one person who makes the party fun"},
  {id:"q099",category:"future",red:"See your most successful possible future",blue:"See the happiest possible future for you"},
  {id:"q100",category:"life",red:"Take the safe path and know it works",blue:"Take the wild path and discover what happens"}
];
